runtime: nodejs18
env: standard
instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
  - url: /.*
    script: auto